
package com.intershop.iom.typesv1_2p;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-11-22T11:23:04.620+01:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "DuplicateException", targetNamespace = "http://types.theberlinbakery.com/v1_0")
public class DuplicateException extends Exception {

    private com.intershop.iom.typesv1_0.DuplicateException faultInfo;

    public DuplicateException() {
        super();
    }

    public DuplicateException(String message) {
        super(message);
    }

    public DuplicateException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DuplicateException(String message, com.intershop.iom.typesv1_0.DuplicateException duplicateException) {
        super(message);
        this.faultInfo = duplicateException;
    }

    public DuplicateException(String message, com.intershop.iom.typesv1_0.DuplicateException duplicateException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = duplicateException;
    }

    public com.intershop.iom.typesv1_0.DuplicateException getFaultInfo() {
        return this.faultInfo;
    }
}
