
package com.intershop.iom.typesv1_2p;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-11-22T11:23:04.672+01:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "InvalidMessageException", targetNamespace = "http://types.theberlinbakery.com/v1_0")
public class InvalidMessageException extends Exception {

    private com.intershop.iom.typesv1_0.InvalidMessageException faultInfo;

    public InvalidMessageException() {
        super();
    }

    public InvalidMessageException(String message) {
        super(message);
    }

    public InvalidMessageException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidMessageException(String message, com.intershop.iom.typesv1_0.InvalidMessageException invalidMessageException) {
        super(message);
        this.faultInfo = invalidMessageException;
    }

    public InvalidMessageException(String message, com.intershop.iom.typesv1_0.InvalidMessageException invalidMessageException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidMessageException;
    }

    public com.intershop.iom.typesv1_0.InvalidMessageException getFaultInfo() {
        return this.faultInfo;
    }
}
