
package com.intershop.iom.typesv1_2p;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-11-22T11:23:04.680+01:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "TechnicalException", targetNamespace = "http://types.theberlinbakery.com/v1_0")
public class TechnicalException extends Exception {

    private com.intershop.iom.typesv1_0.TechnicalException faultInfo;

    public TechnicalException() {
        super();
    }

    public TechnicalException(String message) {
        super(message);
    }

    public TechnicalException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public TechnicalException(String message, com.intershop.iom.typesv1_0.TechnicalException technicalException) {
        super(message);
        this.faultInfo = technicalException;
    }

    public TechnicalException(String message, com.intershop.iom.typesv1_0.TechnicalException technicalException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = technicalException;
    }

    public com.intershop.iom.typesv1_0.TechnicalException getFaultInfo() {
        return this.faultInfo;
    }
}
